version: '3'

services:
  ### MariaDB ##############################################
  mariadb:
    build:
      context: ./mariadb
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ./mariadb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - TZ=UTC
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - app-network
    restart: always

  ### MySQL ##############################################
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - db:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network

### Redis ##################################################
  redis:
    build: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - app-network
    restart: always

  redis-webui:
    build:
      context: ./redis-webui
    environment:
      - ADMIN_USER=${REDIS_WEBUI_USERNAME}
      - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
      - REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST}
      - REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT}
    networks:
      - app-network
    ports:
      - "${REDIS_WEBUI_PORT}:80"
    depends_on:
      - redis
    restart: always

#Docker Networks
networks:
  app-network:
    name: docker-api
    driver: bridge

#Docker Volumes
volumes:
  db:
    driver: local